name: Firebase Continous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/checkout/setup-node@main
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - uses: w9jds/firebase-action@main
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
